services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: 192.168.233.39
      DATABASE_PORT: 5432
      DATABASE_NAME: vochm
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1122
    volumes:
      # Mount config directory so passwords.yaml is available in the container at /config
      - ./config:/config

volumes:
  postgres_data:
