permissions:
  contents: read
  packages: write

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Run Flutter Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Load Flutter dependencies
        working-directory: ./vochm/vochm_flutter
        run: flutter pub get

      - name: Run tests
        working-directory: ./vochm/vochm_flutter
        run: flutter test --no-pub

#  build:
#    name: Build Docker Image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.CR_PAT || secrets.GITHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: ./vochm/vochm_server
#          file: ./vochm/vochm_server/Dockerfile
#          push: true
#          tags: |
#            ghcr.io/niclasje/vochm:latest
#            ghcr.io/niclasje/vochm:${{ github.sha }}

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd backend
            ./deploy.sh
